Issue 5 app navigation
dherranz1/RSS-Aggregator pull request #19
Opened 2022-12-09 21:34 UTC by dherranz1

## Description de la tarea

Se pide desarrollar la estructura de las distintas vistas que formarán la aplicación y el menú principal que permitirá visualizar cada una de ellas. La navegación entre las distintas pantallas se hará con el componente Navigation y el uso del componente BottomNavigationView.

## ¿Cómo se ha implementado?

En primer lugar se agregan todas las dependencias necesarias para usar los componentes de navigation, bottomNavigationView y safe args.

Se crean los siguientes fragmentos:

- RssFeedFragment
- RssManagementFragment
- ProfileFragment

Además se agregan los respectivos layouts: fragment_rss_feed, fragment_rss_managment, fragment_profile.

Se agrega el host de navegación y el BottomNavigationView en el activity_main.xml .

Por otra parte se crea el menú que usará el componente BottomNavigationView.

Posteriormente se agrega el grafo de navegación, estableciendo como inicial el fragmento destinado a cargar la lista de rss.

Se establece el comportamiento que debe tener el menú, indicando a qué fragmento debe navegar según qué item sea seleccionado.

## Keywords

- Navigation
- BottomNavigationView
- Safe Args

## Screenshots or Video

[navigation.webm](https://user-images.githubusercontent.com/114154511/206799372-ca7973d1-dcda-4e8e-b8f8-93491e0f3b58.webm)

## Objetivos

## Criterios de Evaluación

2022-12-15 16:06 UTC, MiM14 requested changes
Buenas tardes Daniel, perdona el retraso con la corrección pero ya me he puesto con ello.
Has hecho una buena pr, sin embargo tengo un par de comentarios.

- Esto es una sugerencia porque me parece algo nimio, pero ten cuidado con el naming de las pr. La pr esta bien documentada a excepción del titulo.

- Faltan tareas de la issue, no has implementado safe args y si no lo haces ahora acabarás teniendo que hacerlo en otro punto del proyecto y por el bien de las estimaciones del ticket te recomiendo añadirla ya.

2022-12-15 16:06 UTC, MiM14 commented on app/src/main/java/com/dherranz1/rss_aggregator/MainActivity.kt
> +            }
Falta por implementar safe args

2022-12-15 16:06 UTC, MiM14 commented on app/src/main/res/navigation/nav_graph.xml
> +
Añade aquí los actions para el safe args y listo

2022-12-16 11:57 UTC, dherranz1 commented on app/src/main/java/com/dherranz1/rss_aggregator/MainActivity.kt
> +            }
Lo comentado en clase en persona, pensaba que era únicamente para pasar información entre fragmentos con seguridad. Dado que no se pasa información a ningún otro fragmento y únicamente se cambia de uno a otro, pensé que sería para pasar información a otro nuevo fragmento sugerido en algún futuro ticket, ya que en el ticket pone agregar safe arg y no hacer uso de safe arg, de ahí la confusión. Consideré por tanto innecesario el uso y por tanto sólo agregué.

Revisando más detenidamente la documentación sobre safe args, sí parece afectar más allá del paso de información.

Hago la adaptación sin problema :rocket:

2022-12-16 14:19 UTC, josem-perram commented on app/src/main/java/com/dherranz1/rss_aggregator/MainActivity.kt
> +            }
Hola Daniel, safe args cuando haya argumentos y safe nav cuando sólo haya navegación.

2022-12-16 14:20 UTC, josem-perram requested changes
De acuerdo con los comentarios de @MiM14 , por favor, revisa la parte de safe navigations.

2022-12-17 17:31 UTC, dherranz1 commented on app/src/main/java/com/dherranz1/rss_aggregator/MainActivity.kt
> +            }
uso de navgraphdirections para la navegación agregado

2022-12-17 17:31 UTC, dherranz1 commented on app/src/main/res/navigation/nav_graph.xml
> +
actions agregadas

2022-12-18 11:16 UTC, MiM14 approved these changes
✅

2023-01-07 16:31 UTC, josem-perram approved these changes
🚀

2023-01-10 11:47 UTC, merged